name: Deploy to Main Branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout_and_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16'

  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy to hosting server
        run: |
          echo "Deploy..."
